build:
  maxIssues: 0

formatting:
  MultiLineIfElse:
    active: false
  NoWildcardImports:
    active: false

complexity:
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 9
  NestedBlockDepth:
    threshold: 6

style:
  WildcardImport:
    active: false
  ThrowsCount:
    max: 4
